#
# ##docker 1.5 on ubuntu##
# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
#
# sudo sh -c "echo deb https://get.docker.io/ubuntu docker main  > /etc/apt/sources.list.d/docker.list"
# $ sudo apt-get update
# $ sudo apt-get install lxc-docker
#

nginx:
#  image: jwilder/nginx-proxy
  build: ./nginx-proxy
  privileged: true
  ports:
  - "80:80"
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  - ./nginx-data/htpasswd:/etc/nginx/htpasswd
  - ./nginx-data/certs:/etc/nginx/certs
  - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx-data/vhost.d:/etc/nginx/vhost.d
  - ./nginx-data/error-pages:/usr/local/nginx/html
  environment:
  - LOG=true
  - LOG_TAG=strip.parse.nginx.access
  links:
  - fluentd

logrotate:
  build: ./logrotate
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /var/lib/docker:/var/lib/docker
  environment:
  - LOG=true

kibana:
  image: balsamiq/docker-kibana
  #build: ./docker-kibana
  environment:
  - VIRTUAL_HOST=kibana.*
  - KIBANA_SECURE=false
  expose:
  - "80"
  links:
   - elasticsearch:es

elasticsearch:
  image: library/elasticsearch
  expose:
  - "9200"
  - "9300"
  volumes:
  - ./elastic-data:/data
  command: /elasticsearch/bin/elasticsearch -Des.config=/data/elasticsearch.yml
  environment:
  - LOG=true 

fluentd:
  build: ./fluentd
  environment:
  - ES_HOST=elasticsearch
  - ES_PORT=9200
  links:
  - elasticsearch
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  - /var/lib/docker:/var/lib/docker
  - ./fluentd-data/config/:/app/config/
# sudo docker run   -e ES_HOST=elasticsearch   -e ES_PORT=9200   -p 9292:9292  --link  Harbour_elasticsearch_1:elasticsearch  pblittle/docker-logstash 




